import type { PRDescriptionParams } from './types';

/**
 * Generate smart branch name from rule and file
 */
export function generateBranchName(ruleId: string, filePath: string | null, lineNumber?: number): string {
  // Sanitize rule ID for branch name
  const rule = ruleId.replace(/[^a-z0-9-]/gi, '-').toLowerCase();

  // Get file name without extension
  const fileName = filePath
    ? filePath.split('/').pop()?.replace(/\.[^/.]+$/, '').replace(/[^a-z0-9]/gi, '-').toLowerCase()
    : 'fix';

  // Create unique suffix from timestamp
  const suffix = Date.now().toString(36).slice(-4);

  // Include line number if available
  const lineStr = lineNumber ? `-L${lineNumber}` : '';

  return `fix/a11y-${rule}-${fileName}${lineStr}-${suffix}`;
}

/**
 * Generate PR description with accessibility fix details
 */
export function generatePRDescription(params: PRDescriptionParams): string {
  const {
    ruleId,
    ruleTitle,
    wcagLevel,
    wcagCriteria,
    filePath,
    lineStart,
    lineEnd,
    originalCode,
    fixedCode,
    scanUrl,
  } = params;

  const lineInfo = lineStart
    ? lineEnd && lineEnd !== lineStart
      ? `Lines ${lineStart}-${lineEnd}`
      : `Line ${lineStart}`
    : '';

  const wcagInfo = wcagLevel || wcagCriteria
    ? `\n**WCAG:** ${wcagCriteria || ''} ${wcagLevel ? `(Level ${wcagLevel.toUpperCase()})` : ''}`
    : '';

  return `## ♿ Accessibility Fix

This PR fixes an accessibility issue detected by [AllyLab](https://allylab.io).

### 🔍 Issue Details
**Rule:** ${ruleId || 'accessibility'} - ${ruleTitle}${wcagInfo}

### 📁 Changes
**File:** \`${filePath}\`${lineInfo ? `\n**Location:** ${lineInfo}` : ''}

<details>
<summary>View code changes</summary>

**Before:**
\`\`\`html
${originalCode}
\`\`\`

**After:**
\`\`\`html
${fixedCode}
\`\`\`

</details>

### ✅ Review Checklist
- [ ] Visual appearance is correct
- [ ] Screen reader announces content properly
- [ ] Keyboard navigation works as expected
- [ ] Color contrast meets WCAG requirements
- [ ] No new accessibility issues introduced

### 🔗 References
${scanUrl ? `- [View scan results](${scanUrl})\n` : ''}- [WCAG Guidelines](https://www.w3.org/WAI/WCAG21/quickref/)
${ruleId ? `- [${ruleId} rule documentation](https://dequeuniversity.com/rules/axe/4.4/${ruleId})` : ''}

---
*🤖 Generated by [AllyLab](https://allylab.io) • Powered by Claude AI*`;
}
