import type jsPDF from 'jspdf';

export function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 0, g: 0, b: 0 };
}

export function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + '...';
}

export function createPageBreakChecker(
  pdf: jsPDF,
  margin: number,
  getYPosition: () => number,
  setYPosition: (y: number) => void
) {
  const pageHeight = pdf.internal.pageSize.getHeight();

  return (requiredHeight: number): boolean => {
    if (getYPosition() + requiredHeight > pageHeight - margin) {
      pdf.addPage();
      setYPosition(margin);
      return true;
    }
    return false;
  };
}

export function addPdfFooter(pdf: jsPDF, margin: number): void {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const totalPages = pdf.internal.pages.length - 1;

  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, {
      align: 'center',
    });
    pdf.text('Generated by AllyLab', pageWidth - margin, pageHeight - 10, {
      align: 'right',
    });
  }
}

export function addPdfHeader(
  pdf: jsPDF,
  margin: number,
  companyName: string,
  title: string,
  subtitle?: string
): number {
  let yPosition = margin;

  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(companyName, margin, yPosition);
  yPosition += 10;

  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'normal');
  pdf.text(title, margin, yPosition);
  yPosition += 8;

  if (subtitle) {
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text(subtitle, margin, yPosition);
    pdf.setTextColor(0);
    yPosition += 15;
  } else {
    yPosition += 7;
  }

  return yPosition;
}

export interface TableColumn {
  header: string;
  width: number;
}

export function drawTableHeader(
  pdf: jsPDF,
  columns: TableColumn[],
  margin: number,
  yPosition: number
): void {
  const pageWidth = pdf.internal.pageSize.getWidth();

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setFillColor(241, 245, 249);
  pdf.rect(margin, yPosition - 4, pageWidth - 2 * margin, 8, 'F');

  let xPos = margin;
  columns.forEach((col) => {
    pdf.text(col.header, xPos + 2, yPosition);
    xPos += col.width;
  });
}

export function drawTableRow(
  pdf: jsPDF,
  data: string[],
  columnWidths: number[],
  margin: number,
  yPosition: number,
  isAlternate: boolean
): void {
  const pageWidth = pdf.internal.pageSize.getWidth();

  if (isAlternate) {
    pdf.setFillColor(248, 250, 252);
    pdf.rect(margin, yPosition - 4, pageWidth - 2 * margin, 7, 'F');
  }

  let xPos = margin;
  data.forEach((cell, i) => {
    pdf.text(cell, xPos + 2, yPosition);
    xPos += columnWidths[i];
  });
}
