/**
 * Demo Tour Component
 *
 * Provides a guided walkthrough of the dashboard for new users in demo mode.
 * Uses a step-by-step approach with highlights and tooltips.
 */

import { useState, useEffect, useCallback } from 'react';
import { X, ChevronLeft, ChevronRight, Sparkles } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';

interface TourStep {
  target: string;
  title: string;
  content: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
}

const TOUR_STEPS: TourStep[] = [
  {
    target: '[data-tour="scan-input"]',
    title: 'Start a Scan',
    content: 'Enter any URL to scan for accessibility issues. AllyLab checks against WCAG 2.2 guidelines.',
    position: 'bottom',
  },
  {
    target: '[data-tour="scan-button"]',
    title: 'Run the Scan',
    content: 'Click to start scanning. You\'ll see real-time progress as we analyze the page.',
    position: 'bottom',
  },
  {
    target: '[data-tour="score-display"]',
    title: 'Accessibility Score',
    content: 'Your overall accessibility score based on the issues found. Aim for 90+ for good compliance.',
    position: 'left',
  },
  {
    target: '[data-tour="findings-table"]',
    title: 'Review Findings',
    content: 'All accessibility issues are listed here with severity, affected elements, and WCAG criteria.',
    position: 'top',
  },
  {
    target: '[data-tour="ai-fix"]',
    title: 'AI-Powered Fixes',
    content: 'Get production-ready code fixes generated by AI. One click to fix accessibility issues.',
    position: 'left',
  },
  {
    target: '[data-tour="github-pr"]',
    title: 'Create Pull Requests',
    content: 'Push fixes directly to GitHub. Create PRs with all the fixes applied automatically.',
    position: 'left',
  },
  {
    target: '[data-tour="sidebar-settings"]',
    title: 'Configure Settings',
    content: 'Set up integrations, schedules, webhooks, and custom rules to automate your workflow.',
    position: 'right',
  },
  {
    target: '[data-tour="sidebar-reports"]',
    title: 'Track Progress',
    content: 'View trends, compare scans, and export reports to track accessibility improvements over time.',
    position: 'right',
  },
];

const TOUR_STORAGE_KEY = 'allylab_demo_tour_completed';

export function DemoTour() {
  const { isMockAuth } = useAuth();
  const [isActive, setIsActive] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [highlightRect, setHighlightRect] = useState<DOMRect | null>(null);

  // Check if tour should be shown
  useEffect(() => {
    if (!isMockAuth) return;

    const hasCompletedTour = localStorage.getItem(TOUR_STORAGE_KEY);
    if (!hasCompletedTour) {
      // Delay tour start to let the UI settle
      const timer = setTimeout(() => {
        setIsActive(true);
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [isMockAuth]);

  // Update highlight position
  const updateHighlight = useCallback(() => {
    if (!isActive) return;

    const step = TOUR_STEPS[currentStep];
    const element = document.querySelector(step.target);

    if (element) {
      const rect = element.getBoundingClientRect();
      setHighlightRect(rect);
    } else {
      setHighlightRect(null);
    }
  }, [currentStep, isActive]);

  useEffect(() => {
    // Initial highlight update - needed to sync with external DOM position
    // eslint-disable-next-line react-hooks/set-state-in-effect
    updateHighlight();

    // Update on resize and scroll
    window.addEventListener('resize', updateHighlight);
    window.addEventListener('scroll', updateHighlight, true);

    return () => {
      window.removeEventListener('resize', updateHighlight);
      window.removeEventListener('scroll', updateHighlight, true);
    };
  }, [updateHighlight]);

  const handleNext = () => {
    if (currentStep < TOUR_STEPS.length - 1) {
      setCurrentStep(currentStep + 1);
    } else {
      handleComplete();
    }
  };

  const handlePrev = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleComplete = () => {
    localStorage.setItem(TOUR_STORAGE_KEY, 'true');
    setIsActive(false);
  };

  const handleSkip = () => {
    localStorage.setItem(TOUR_STORAGE_KEY, 'true');
    setIsActive(false);
  };

  const handleRestart = () => {
    localStorage.removeItem(TOUR_STORAGE_KEY);
    setCurrentStep(0);
    setIsActive(true);
  };

  if (!isActive) {
    // Show restart button when tour is not active but we're in demo mode
    if (isMockAuth) {
      return (
        <button
          onClick={handleRestart}
          className="fixed bottom-4 left-4 z-40 flex items-center gap-2 px-3 py-2 bg-primary/10 hover:bg-primary/20 border border-primary/30 rounded-lg text-sm text-primary transition-colors"
          aria-label="Restart tour"
        >
          <Sparkles size={16} />
          <span className="hidden sm:inline">Take a tour</span>
        </button>
      );
    }
    return null;
  }

  const step = TOUR_STEPS[currentStep];
  const tooltipStyle = getTooltipStyle(highlightRect, step.position || 'bottom');

  return (
    <>
      {/* Overlay */}
      <div className="fixed inset-0 z-50 pointer-events-none">
        {/* Dark overlay with cutout */}
        <svg className="absolute inset-0 w-full h-full">
          <defs>
            <mask id="tour-mask">
              <rect x="0" y="0" width="100%" height="100%" fill="white" />
              {highlightRect && (
                <rect
                  x={highlightRect.left - 8}
                  y={highlightRect.top - 8}
                  width={highlightRect.width + 16}
                  height={highlightRect.height + 16}
                  rx="8"
                  fill="black"
                />
              )}
            </mask>
          </defs>
          <rect
            x="0"
            y="0"
            width="100%"
            height="100%"
            fill="rgba(0, 0, 0, 0.75)"
            mask="url(#tour-mask)"
          />
        </svg>

        {/* Highlight ring */}
        {highlightRect && (
          <div
            className="absolute border-2 border-primary rounded-lg pointer-events-none animate-pulse"
            style={{
              left: highlightRect.left - 8,
              top: highlightRect.top - 8,
              width: highlightRect.width + 16,
              height: highlightRect.height + 16,
            }}
          />
        )}

        {/* Tooltip */}
        <div
          className="absolute bg-surface border border-border rounded-xl shadow-2xl p-4 max-w-sm pointer-events-auto"
          style={tooltipStyle}
        >
          {/* Header */}
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <Sparkles size={18} className="text-primary" />
              <h3 className="font-semibold text-text-primary">{step.title}</h3>
            </div>
            <button
              onClick={handleSkip}
              className="text-text-muted hover:text-text-primary p-1"
              aria-label="Close tour"
            >
              <X size={18} />
            </button>
          </div>

          {/* Content */}
          <p className="text-text-secondary text-sm mb-4">{step.content}</p>

          {/* Footer */}
          <div className="flex items-center justify-between">
            <span className="text-xs text-text-muted">
              {currentStep + 1} of {TOUR_STEPS.length}
            </span>
            <div className="flex gap-2">
              {currentStep > 0 && (
                <button
                  onClick={handlePrev}
                  className="flex items-center gap-1 px-3 py-1.5 text-sm bg-surface-secondary hover:bg-surface-tertiary border border-border rounded-lg transition-colors"
                >
                  <ChevronLeft size={16} />
                  Back
                </button>
              )}
              <button
                onClick={handleNext}
                className="flex items-center gap-1 px-3 py-1.5 text-sm bg-primary hover:bg-primary/90 text-black rounded-lg transition-colors"
              >
                {currentStep === TOUR_STEPS.length - 1 ? 'Finish' : 'Next'}
                {currentStep < TOUR_STEPS.length - 1 && <ChevronRight size={16} />}
              </button>
            </div>
          </div>

          {/* Progress dots */}
          <div className="flex justify-center gap-1 mt-4">
            {TOUR_STEPS.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentStep(index)}
                className={`w-2 h-2 rounded-full transition-colors ${
                  index === currentStep ? 'bg-primary' : 'bg-border hover:bg-text-muted'
                }`}
                aria-label={`Go to step ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

function getTooltipStyle(
  rect: DOMRect | null,
  position: 'top' | 'bottom' | 'left' | 'right'
): React.CSSProperties {
  if (!rect) {
    return {
      left: '50%',
      top: '50%',
      transform: 'translate(-50%, -50%)',
    };
  }

  const offset = 20;

  switch (position) {
    case 'top':
      return {
        left: rect.left + rect.width / 2,
        top: rect.top - offset,
        transform: 'translate(-50%, -100%)',
      };
    case 'bottom':
      return {
        left: rect.left + rect.width / 2,
        top: rect.bottom + offset,
        transform: 'translateX(-50%)',
      };
    case 'left':
      return {
        left: rect.left - offset,
        top: rect.top + rect.height / 2,
        transform: 'translate(-100%, -50%)',
      };
    case 'right':
      return {
        left: rect.right + offset,
        top: rect.top + rect.height / 2,
        transform: 'translateY(-50%)',
      };
    default:
      return {
        left: rect.left + rect.width / 2,
        top: rect.bottom + offset,
        transform: 'translateX(-50%)',
      };
  }
}

export function useTourAttributes() {
  return {
    scanInput: { 'data-tour': 'scan-input' },
    scanButton: { 'data-tour': 'scan-button' },
    scoreDisplay: { 'data-tour': 'score-display' },
    findingsTable: { 'data-tour': 'findings-table' },
    aiFix: { 'data-tour': 'ai-fix' },
    githubPr: { 'data-tour': 'github-pr' },
    sidebarSettings: { 'data-tour': 'sidebar-settings' },
    sidebarReports: { 'data-tour': 'sidebar-reports' },
  };
}
