import type { FindingWithFix } from '../types/batch-pr';

export function generateBatchDescription(fixes: FindingWithFix[]): string {
  const issuesList = fixes
    .map(f => `- **${f.finding.ruleTitle}** in \`${f.filePath}\``)
    .join('\n');

  const bySeverity = {
    critical: fixes.filter(f => f.finding.impact === 'critical').length,
    serious: fixes.filter(f => f.finding.impact === 'serious').length,
    moderate: fixes.filter(f => f.finding.impact === 'moderate').length,
    minor: fixes.filter(f => f.finding.impact === 'minor').length,
  };

  return `## 🔧 Batch Accessibility Fixes

This PR was automatically generated by [AllyLab](https://github.com/jorgejac1/allylab) to fix ${fixes.length} accessibility issues.

### Summary
| Severity | Count |
|----------|-------|
| 🔴 Critical | ${bySeverity.critical} |
| 🟠 Serious | ${bySeverity.serious} |
| 🟡 Moderate | ${bySeverity.moderate} |
| 🔵 Minor | ${bySeverity.minor} |

### Issues Fixed
${issuesList}

### Review Checklist
- [ ] Verify fixes render correctly
- [ ] Test with screen reader
- [ ] Check keyboard navigation
- [ ] Run accessibility scan to confirm

---
*Generated by AllyLab • Powered by Claude AI*`;
}