import type { FindingWithFix } from '../types/batch-pr';

/**
 * Generate a smart PR title based on the fixes
 */
export function generateSmartTitle(fixes: FindingWithFix[]): string {
  const count = fixes.length;
  
  if (count === 0) {
    return '♿ Fix accessibility issues';
  }
  
  // Group by rule type
  const ruleGroups: Record<string, number> = {};
  fixes.forEach(f => {
    const ruleId = f.finding.ruleId || 'accessibility';
    ruleGroups[ruleId] = (ruleGroups[ruleId] || 0) + 1;
  });
  
  const ruleTypes = Object.keys(ruleGroups);
  
  // If all same rule type, be specific
  if (ruleTypes.length === 1) {
    const ruleId = ruleTypes[0];
    const ruleName = formatRuleName(ruleId);
    return `♿ Fix ${count} ${ruleName} issue${count > 1 ? 's' : ''}`;
  }
  
  // If 2-3 different rules, list them
  if (ruleTypes.length <= 3) {
    const ruleNames = ruleTypes.map(formatRuleName).join(', ');
    return `♿ Fix ${count} accessibility issues (${ruleNames})`;
  }
  
  // Generic title for many different rules
  return `♿ Fix ${count} accessibility issue${count > 1 ? 's' : ''}`;
}

/**
 * Format rule ID into human-readable name
 */
function formatRuleName(ruleId: string): string {
  return ruleId
    .replace(/-/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .replace(/Aria/g, 'ARIA')
    .replace(/Alt/g, 'Alt')
    .replace(/Wcag/g, 'WCAG');
}

/**
 * Generate smart branch name for batch PR
 */
export function generateSmartBranchName(fixes: FindingWithFix[]): string {
  const count = fixes.length;
  const suffix = Date.now().toString(36).slice(-4);
  
  // Group by rule type
  const ruleGroups: Record<string, number> = {};
  fixes.forEach(f => {
    const ruleId = f.finding.ruleId || 'a11y';
    ruleGroups[ruleId] = (ruleGroups[ruleId] || 0) + 1;
  });
  
  const ruleTypes = Object.keys(ruleGroups);
  
  // If all same rule type, use it in branch name
  if (ruleTypes.length === 1) {
    const rule = ruleTypes[0].replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    return `fix/a11y-batch-${count}-${rule}-${suffix}`;
  }
  
  // Generic batch branch name
  return `fix/a11y-batch-${count}-issues-${suffix}`;
}

/**
 * Generate enhanced batch PR description
 */
export function generateBatchDescription(fixes: FindingWithFix[], scanUrl?: string): string {
  // Group fixes by file
  const byFile: Record<string, FindingWithFix[]> = {};
  fixes.forEach(f => {
    const file = f.filePath || 'Unknown';
    if (!byFile[file]) byFile[file] = [];
    byFile[file].push(f);
  });

  // Generate file changes section
  const fileChanges = Object.entries(byFile)
    .map(([file, fileFixes]) => {
      const fixList = fileFixes
        .map(f => `  - ${f.finding.ruleTitle}`)
        .join('\n');
      return `- \`${file}\` (${fileFixes.length} fix${fileFixes.length > 1 ? 'es' : ''})\n${fixList}`;
    })
    .join('\n\n');

  // Count by severity
  const bySeverity = {
    critical: fixes.filter(f => f.finding.impact === 'critical').length,
    serious: fixes.filter(f => f.finding.impact === 'serious').length,
    moderate: fixes.filter(f => f.finding.impact === 'moderate').length,
    minor: fixes.filter(f => f.finding.impact === 'minor').length,
  };

  // Count by rule type
  const byRule: Record<string, number> = {};
  fixes.forEach(f => {
    const rule = f.finding.ruleId || f.finding.ruleTitle;
    byRule[rule] = (byRule[rule] || 0) + 1;
  });

  const ruleBreakdown = Object.entries(byRule)
    .sort((a, b) => b[1] - a[1])
    .map(([rule, count]) => `| ${rule} | ${count} |`)
    .join('\n');

  return `## ♿ Batch Accessibility Fixes

This PR fixes **${fixes.length} accessibility issue${fixes.length > 1 ? 's'  : ''}** detected by [AllyLab](https://allylab.io).

### 📊 Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${bySeverity.critical} |
| 🟠 Serious | ${bySeverity.serious} |
| 🟡 Moderate | ${bySeverity.moderate} |
| 🔵 Minor | ${bySeverity.minor} |

<details>
<summary>Issues by Rule Type</summary>

| Rule | Count |
|------|-------|
${ruleBreakdown}

</details>

### 📁 Files Changed

${fileChanges}

<details>
<summary>View all code changes</summary>

${fixes.map((f, i) => `
#### ${i + 1}. ${f.finding.ruleTitle}
**File:** \`${f.filePath}\`

**Before:**
\`\`\`html
${f.fix?.original.code || 'N/A'}
\`\`\`

**After:**
\`\`\`html
${f.fix?.fixes.html || 'N/A'}
\`\`\`
`).join('\n---\n')}

</details>

### ✅ Review Checklist

- [ ] Visual appearance is correct for all changes
- [ ] Screen reader announces content properly
- [ ] Keyboard navigation works as expected
- [ ] Color contrast meets WCAG requirements
- [ ] No new accessibility issues introduced

### 🔗 References

${scanUrl ? `- [View scan results](${scanUrl})\n` : ''}- [WCAG Guidelines](https://www.w3.org/WAI/WCAG21/quickref/)
- [Deque University](https://dequeuniversity.com/)

---
*🤖 Generated by [AllyLab](https://allylab.io) • Powered by Claude AI*`;
}