const loadJsPDF = () => import("jspdf").then((m) => m.default);
const loadHtml2Canvas = () => import("html2canvas").then((m) => m.default);
import type { PDFDashboardData, SiteStats, TopIssue } from "../types/executive";

interface PDFReportOptions {
  title?: string;
  dateRange?: string;
  companyName?: string;
}

const COLORS = {
  primary: "#1e3a5f",
  secondary: "#2563eb",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  gray: "#64748b",
  lightGray: "#f1f5f9",
  white: "#ffffff",
};

const SEVERITY_COLORS = {
  critical: "#dc2626",
  serious: "#ea580c",
  moderate: "#ca8a04",
  minor: "#2563eb",
};

export async function generateExecutiveReportPDF(
  data: PDFDashboardData,
  sites: SiteStats[],
  topIssues: TopIssue[],
  options: PDFReportOptions = {}
): Promise<void> {
  const {
    title = "Accessibility Executive Report",
    dateRange = `Generated on ${new Date().toLocaleDateString()}`,
    companyName = "AllyLab",
  } = options;

  // Dynamically load jsPDF
  const jsPDF = await loadJsPDF();
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper functions
  const addPage = () => {
    pdf.addPage();
    y = margin;
    addFooter();
  };

  const checkPageBreak = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - 20) {
      addPage();
    }
  };

  const addFooter = () => {
    const pageCount = pdf.getNumberOfPages();
    pdf.setFontSize(8);
    pdf.setTextColor(COLORS.gray);
    pdf.text(
      `Generated by ${companyName} | Page ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  };

  // ============================================
  // HEADER
  // ============================================

  // Background header bar
  pdf.setFillColor(COLORS.primary);
  pdf.rect(0, 0, pageWidth, 40, "F");

  // Logo/Company name
  pdf.setTextColor(COLORS.white);
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("🔍 " + companyName, margin, 18);

  // Title
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "normal");
  pdf.text(title, margin, 28);

  // Date
  pdf.setFontSize(10);
  pdf.text(dateRange, margin, 35);

  y = 50;

  // ============================================
  // SCORE SUMMARY CARDS
  // ============================================

  pdf.setTextColor(COLORS.primary);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Executive Summary", margin, y);
  y += 10;

  const cardWidth = (contentWidth - 15) / 4;
  const cardHeight = 25;
  const cards = [
    {
      label: "Average Score",
      value: `${data.averageScore}`,
      color: getScoreColor(data.averageScore),
    },
    { label: "Total Issues", value: `${data.totalIssues}`, color: COLORS.gray },
    {
      label: "Critical Issues",
      value: `${data.severity.critical}`,
      color: COLORS.danger,
    },
    {
      label: "Sites Monitored",
      value: `${data.sitesMonitored}`,
      color: COLORS.secondary,
    },
  ];

  cards.forEach((card, index) => {
    const x = margin + index * (cardWidth + 5);

    // Card background
    pdf.setFillColor(COLORS.lightGray);
    pdf.roundedRect(x, y, cardWidth, cardHeight, 3, 3, "F");

    // Value
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(card.color);
    pdf.text(card.value, x + cardWidth / 2, y + 12, { align: "center" });

    // Label
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(COLORS.gray);
    pdf.text(card.label, x + cardWidth / 2, y + 20, { align: "center" });
  });

  y += cardHeight + 15;

  // ============================================
  // SEVERITY DISTRIBUTION
  // ============================================

  checkPageBreak(40);

  pdf.setTextColor(COLORS.primary);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Issue Severity Distribution", margin, y);
  y += 8;

  const totalSeverity =
    data.severity.critical +
    data.severity.serious +
    data.severity.moderate +
    data.severity.minor;
  const severityData = [
    {
      label: "Critical",
      count: data.severity.critical,
      color: SEVERITY_COLORS.critical,
    },
    {
      label: "Serious",
      count: data.severity.serious,
      color: SEVERITY_COLORS.serious,
    },
    {
      label: "Moderate",
      count: data.severity.moderate,
      color: SEVERITY_COLORS.moderate,
    },
    {
      label: "Minor",
      count: data.severity.minor,
      color: SEVERITY_COLORS.minor,
    },
  ];

  // Draw stacked bar
  let barX = margin;
  const barHeight = 12;

  severityData.forEach((item) => {
    const barWidth =
      totalSeverity > 0 ? (item.count / totalSeverity) * contentWidth : 0;
    if (barWidth > 0) {
      pdf.setFillColor(item.color);
      pdf.rect(barX, y, barWidth, barHeight, "F");
      barX += barWidth;
    }
  });

  y += barHeight + 5;

  // Legend
  let legendX = margin;
  severityData.forEach((item) => {
    pdf.setFillColor(item.color);
    pdf.rect(legendX, y, 8, 4, "F");
    pdf.setFontSize(8);
    pdf.setTextColor(COLORS.gray);
    pdf.text(`${item.label}: ${item.count}`, legendX + 10, y + 3);
    legendX += 45;
  });

  y += 15;

  // ============================================
  // TOP ISSUES TABLE
  // ============================================

  checkPageBreak(80);

  pdf.setTextColor(COLORS.primary);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Top 10 Issues by Frequency", margin, y);
  y += 8;

  // Table header
  const colWidths = [90, 25, 20, 25];
  const headers = ["Issue", "Severity", "Count", "Sites"];

  pdf.setFillColor(COLORS.primary);
  pdf.rect(margin, y, contentWidth, 8, "F");

  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(COLORS.white);

  let headerX = margin + 3;
  headers.forEach((header, i) => {
    pdf.text(header, headerX, y + 5.5);
    headerX += colWidths[i];
  });

  y += 8;

  // Table rows
  const displayIssues = topIssues.slice(0, 10);
  displayIssues.forEach((issue, index) => {
    checkPageBreak(10);

    const rowColor = index % 2 === 0 ? COLORS.white : COLORS.lightGray;
    pdf.setFillColor(rowColor);
    pdf.rect(margin, y, contentWidth, 8, "F");

    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(COLORS.primary);

    let cellX = margin + 3;

    // Issue title (truncate if needed)
    const title =
      issue.title.length > 45
        ? issue.title.substring(0, 42) + "..."
        : issue.title;
    pdf.text(title, cellX, y + 5.5);
    cellX += colWidths[0];

    // Severity badge
    pdf.setTextColor(SEVERITY_COLORS[issue.severity] || COLORS.gray);
    pdf.setFont("helvetica", "bold");
    pdf.text(issue.severity.toUpperCase(), cellX, y + 5.5);
    cellX += colWidths[1];

    // Count
    pdf.setTextColor(COLORS.primary);
    pdf.setFont("helvetica", "normal");
    pdf.text(String(issue.count), cellX, y + 5.5);
    cellX += colWidths[2];

    // Sites
    pdf.text(String(issue.affectedSites), cellX, y + 5.5);

    y += 8;
  });

  y += 10;

  // ============================================
  // SITE RANKINGS
  // ============================================

  checkPageBreak(60);

  pdf.setTextColor(COLORS.primary);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Site Rankings", margin, y);
  y += 8;

  // Table header
  const siteColWidths = [10, 70, 25, 25, 30];
  const siteHeaders = ["#", "Site", "Score", "Grade", "Issues"];

  pdf.setFillColor(COLORS.primary);
  pdf.rect(margin, y, contentWidth, 8, "F");

  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(COLORS.white);

  let siteHeaderX = margin + 3;
  siteHeaders.forEach((header, i) => {
    pdf.text(header, siteHeaderX, y + 5.5);
    siteHeaderX += siteColWidths[i];
  });

  y += 8;

  // Site rows
  const sortedSites = [...sites].sort((a, b) => a.latestScore - b.latestScore);
  sortedSites.forEach((site, index) => {
    checkPageBreak(10);

    const rowColor = index % 2 === 0 ? COLORS.white : COLORS.lightGray;
    pdf.setFillColor(rowColor);
    pdf.rect(margin, y, contentWidth, 8, "F");

    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");

    let cellX = margin + 3;

    // Rank
    pdf.setTextColor(COLORS.gray);
    pdf.text(String(index + 1), cellX, y + 5.5);
    cellX += siteColWidths[0];

    // Domain
    pdf.setTextColor(COLORS.primary);
    const domain =
      site.domain.length > 35
        ? site.domain.substring(0, 32) + "..."
        : site.domain;
    pdf.text(domain, cellX, y + 5.5);
    cellX += siteColWidths[1];

    // Score
    pdf.setTextColor(getScoreColor(site.latestScore));
    pdf.setFont("helvetica", "bold");
    pdf.text(String(site.latestScore), cellX, y + 5.5);
    cellX += siteColWidths[2];

    // Grade
    const grade = getGrade(site.latestScore);
    pdf.text(grade, cellX, y + 5.5);
    cellX += siteColWidths[3];

    // Issues
    pdf.setTextColor(COLORS.primary);
    pdf.setFont("helvetica", "normal");
    pdf.text(String(site.latestIssues), cellX, y + 5.5);

    y += 8;
  });

  // ============================================
  // FOOTER
  // ============================================

  addFooter();

  // Save the PDF
  const filename = `allylab-executive-report-${
    new Date().toISOString().split("T")[0]
  }.pdf`;
  pdf.save(filename);
}

// Helper functions
function getScoreColor(score: number): string {
  if (score >= 90) return COLORS.success;
  if (score >= 70) return COLORS.warning;
  if (score >= 50) return "#ea580c";
  return COLORS.danger;
}

function getGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

// Export a single scan as PDF
export async function generateScanReportPDF(
  elementId: string,
  filename?: string
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error("Element not found:", elementId);
    return;
  }

  // Dynamically load both libraries
  const [jsPDF, html2canvas] = await Promise.all([
    loadJsPDF(),
    loadHtml2Canvas(),
  ]);

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const imgWidth = pageWidth - 20;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let y = 10;
  let remainingHeight = imgHeight;

  while (remainingHeight > 0) {
    pdf.addImage(imgData, "PNG", 10, y, imgWidth, imgHeight);
    remainingHeight -= pageHeight - 20;

    if (remainingHeight > 0) {
      pdf.addPage();
      y = -(imgHeight - remainingHeight - 10);
    }
  }

  const outputFilename = filename || `allylab-scan-report-${Date.now()}.pdf`;
  pdf.save(outputFilename);
}
