"use client";

import { Section, SectionHeader } from "@/components/layout/Section";
import { Card } from "@/components/ui/Card";
import { motion } from "framer-motion";
import Link from "next/link";

const features = [
  {
    icon: "🔍",
    title: "Multi-Page Scanning",
    description:
      "Crawl and scan entire websites with real-time SSE streaming. Support for WCAG 2.0, 2.1, and 2.2 at all conformance levels.",
    color: "green",
    href: "/features#scanning",
  },
  {
    icon: "🤖",
    title: "AI-Powered Fixes",
    description:
      "Get actionable code fixes generated by Claude AI. Framework-specific suggestions for HTML, React, and Vue with confidence scores.",
    color: "blue",
    href: "/features#ai-fixes",
  },
  {
    icon: "🔗",
    title: "GitHub Integration",
    description:
      "Create pull requests directly from issues. Batch multiple fixes into single PRs and verify fixes after merge automatically.",
    color: "purple",
    href: "/features#github",
  },
  {
    icon: "📊",
    title: "Executive Dashboard",
    description:
      "Track accessibility KPIs, historical trends, and competitor benchmarks. Export reports in PDF, CSV, JSON, or Excel formats.",
    color: "orange",
    href: "/features#reporting",
  },
  {
    icon: "⚡",
    title: "CI/CD Integration",
    description:
      "Native GitHub Actions, GitLab CI, and Harness support. Fail builds on critical issues with configurable thresholds.",
    color: "green",
    href: "/features#cicd",
  },
  {
    icon: "🎯",
    title: "Custom Rules",
    description:
      "Define your own accessibility checks with pattern matching, structure validation, and attribute rules. Extend beyond WCAG.",
    color: "blue",
    href: "/features#custom-rules",
  },
  {
    icon: "📅",
    title: "Scheduled Scans",
    description:
      "Automate recurring scans hourly, daily, weekly, or monthly. Track improvements over time with historical data.",
    color: "purple",
    href: "/features#scheduling",
  },
  {
    icon: "🔔",
    title: "Notifications",
    description:
      "Slack and Microsoft Teams integration with formatted messages. Generic webhooks for custom integrations.",
    color: "orange",
    href: "/features#notifications",
  },
];

const colorClasses = {
  green: "bg-primary/15",
  blue: "bg-accent-blue/15",
  purple: "bg-accent-purple/15",
  orange: "bg-accent-orange/15",
};

export function Features() {
  return (
    <Section className="bg-surface-secondary">
      <SectionHeader
        label="Features"
        title="Everything You Need for WCAG Compliance"
        description="From automated scanning to AI-powered fixes, AllyLab has the tools enterprise teams need to build accessible products."
      />

      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
        {features.map((feature, i) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.05 }}
          >
            <Card className="h-full relative overflow-hidden group">
              <div className="absolute inset-x-0 top-0 h-0.5 bg-gradient-to-r from-transparent via-primary to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <div
                className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl mb-4 ${
                  colorClasses[feature.color as keyof typeof colorClasses]
                }`}
              >
                {feature.icon}
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-text-secondary text-sm mb-4">{feature.description}</p>
              <Link
                href={feature.href}
                className="text-sm text-primary font-medium hover:text-primary-dark transition-colors"
              >
                Learn more →
              </Link>
            </Card>
          </motion.div>
        ))}
      </div>
    </Section>
  );
}