import type { ScanResult, Finding, SiteScanResult, PageResult } from './api.js';

/**
 * Generate an HTML report from scan results
 */
export function toHtml(result: ScanResult): string {
  const scoreColor = getScoreColor(result.score);
  const scoreLabel = getScoreLabel(result.score);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Accessibility Report - ${escapeHtml(result.url)}</title>
  <style>
    ${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>Accessibility Report</h1>
      <p class="timestamp">Generated: ${new Date(result.timestamp).toLocaleString()}</p>
    </header>

    <section class="summary">
      <div class="url-card">
        <h2>Scanned URL</h2>
        <a href="${escapeHtml(result.url)}" target="_blank">${escapeHtml(result.url)}</a>
      </div>

      <div class="score-card">
        <div class="score-circle" style="--score-color: ${scoreColor}">
          <span class="score-value">${result.score}</span>
          <span class="score-max">/100</span>
        </div>
        <div class="score-label" style="color: ${scoreColor}">${scoreLabel}</div>
      </div>

      <div class="stats-grid">
        <div class="stat-card critical">
          <span class="stat-value">${result.critical}</span>
          <span class="stat-label">Critical</span>
        </div>
        <div class="stat-card serious">
          <span class="stat-value">${result.serious}</span>
          <span class="stat-label">Serious</span>
        </div>
        <div class="stat-card moderate">
          <span class="stat-value">${result.moderate}</span>
          <span class="stat-label">Moderate</span>
        </div>
        <div class="stat-card minor">
          <span class="stat-value">${result.minor}</span>
          <span class="stat-label">Minor</span>
        </div>
      </div>
    </section>

    <section class="findings">
      <h2>Findings (${result.totalIssues})</h2>
      ${result.findings.length === 0
        ? '<p class="no-findings">No accessibility issues found.</p>'
        : result.findings.map(finding => renderFinding(finding)).join('')
      }
    </section>

    <footer class="footer">
      <p>Generated by <a href="https://github.com/jorgejac1/allylab">AllyLab</a></p>
      <p>Scan time: ${result.scanTime}ms</p>
    </footer>
  </div>
</body>
</html>`;
}

/**
 * Generate an HTML report from site scan results
 */
export function siteToHtml(result: SiteScanResult): string {
  const scoreColor = getScoreColor(result.averageScore);
  const scoreLabel = getScoreLabel(result.averageScore);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Site Accessibility Report</title>
  <style>
    ${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>Site Accessibility Report</h1>
      <p class="timestamp">Generated: ${new Date().toLocaleString()}</p>
    </header>

    <section class="summary">
      <div class="score-card">
        <div class="score-circle" style="--score-color: ${scoreColor}">
          <span class="score-value">${Math.round(result.averageScore)}</span>
          <span class="score-max">/100</span>
        </div>
        <div class="score-label" style="color: ${scoreColor}">${scoreLabel}</div>
        <div class="score-subtitle">Average Score</div>
      </div>

      <div class="stats-grid">
        <div class="stat-card">
          <span class="stat-value">${result.pagesScanned}</span>
          <span class="stat-label">Pages Scanned</span>
        </div>
        <div class="stat-card critical">
          <span class="stat-value">${result.critical}</span>
          <span class="stat-label">Critical</span>
        </div>
        <div class="stat-card serious">
          <span class="stat-value">${result.serious}</span>
          <span class="stat-label">Serious</span>
        </div>
        <div class="stat-card moderate">
          <span class="stat-value">${result.moderate}</span>
          <span class="stat-label">Moderate</span>
        </div>
        <div class="stat-card minor">
          <span class="stat-value">${result.minor}</span>
          <span class="stat-label">Minor</span>
        </div>
      </div>
    </section>

    <section class="pages">
      <h2>Page Results (${result.pagesScanned})</h2>
      <table class="pages-table">
        <thead>
          <tr>
            <th>URL</th>
            <th>Score</th>
            <th>Issues</th>
            <th>Critical</th>
            <th>Serious</th>
            <th>Moderate</th>
            <th>Minor</th>
          </tr>
        </thead>
        <tbody>
          ${result.results.map(page => renderPageRow(page)).join('')}
        </tbody>
      </table>
    </section>

    <footer class="footer">
      <p>Generated by <a href="https://github.com/jorgejac1/allylab">AllyLab</a></p>
      <p>Total issues: ${result.totalIssues}</p>
    </footer>
  </div>
</body>
</html>`;
}

/**
 * Format HTML report as string
 */
export function formatHtml(result: ScanResult): string {
  return toHtml(result);
}

function renderFinding(finding: Finding): string {
  const impactClass = finding.impact;
  const impactLabel = finding.impact.charAt(0).toUpperCase() + finding.impact.slice(1);

  return `
    <div class="finding ${impactClass}">
      <div class="finding-header">
        <span class="impact-badge ${impactClass}">${impactLabel}</span>
        <h3>${escapeHtml(finding.ruleTitle)}</h3>
      </div>
      <p class="finding-description">${escapeHtml(finding.description)}</p>
      <div class="finding-details">
        <div class="detail">
          <strong>Rule ID:</strong> <code>${escapeHtml(finding.ruleId)}</code>
        </div>
        <div class="detail">
          <strong>Selector:</strong> <code>${escapeHtml(finding.selector)}</code>
        </div>
        <div class="detail">
          <strong>WCAG:</strong> ${finding.wcagTags.map(tag => `<span class="wcag-tag">${escapeHtml(tag)}</span>`).join(' ')}
        </div>
      </div>
      <div class="finding-html">
        <strong>Element:</strong>
        <pre><code>${escapeHtml(finding.html)}</code></pre>
      </div>
      <a href="${escapeHtml(finding.helpUrl)}" target="_blank" class="help-link">Learn more about this issue</a>
    </div>
  `;
}

function renderPageRow(page: PageResult): string {
  const scoreColor = getScoreColor(page.score);
  return `
    <tr>
      <td class="url-cell"><a href="${escapeHtml(page.url)}" target="_blank">${escapeHtml(new URL(page.url).pathname)}</a></td>
      <td class="score-cell" style="color: ${scoreColor}">${page.score}</td>
      <td>${page.totalIssues}</td>
      <td class="critical">${page.critical}</td>
      <td class="serious">${page.serious}</td>
      <td class="moderate">${page.moderate}</td>
      <td class="minor">${page.minor}</td>
    </tr>
  `;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function getScoreColor(score: number): string {
  if (score >= 90) return '#22c55e';
  if (score >= 70) return '#eab308';
  if (score >= 50) return '#f97316';
  return '#ef4444';
}

function getScoreLabel(score: number): string {
  if (score >= 90) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Needs Work';
  return 'Poor';
}

function getStyles(): string {
  return `
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #f3f4f6;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }
    .header {
      text-align: center;
      margin-bottom: 2rem;
    }
    .header h1 {
      font-size: 2rem;
      color: #1f2937;
      margin-bottom: 0.5rem;
    }
    .timestamp {
      color: #6b7280;
      font-size: 0.875rem;
    }
    .summary {
      background: white;
      border-radius: 12px;
      padding: 2rem;
      margin-bottom: 2rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .url-card {
      margin-bottom: 1.5rem;
      padding-bottom: 1.5rem;
      border-bottom: 1px solid #e5e7eb;
    }
    .url-card h2 {
      font-size: 0.875rem;
      color: #6b7280;
      margin-bottom: 0.5rem;
    }
    .url-card a {
      color: #2563eb;
      word-break: break-all;
    }
    .score-card {
      text-align: center;
      margin-bottom: 2rem;
    }
    .score-circle {
      display: inline-flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 120px;
      height: 120px;
      border-radius: 50%;
      border: 8px solid var(--score-color);
      margin-bottom: 0.5rem;
    }
    .score-value {
      font-size: 2.5rem;
      font-weight: bold;
      color: var(--score-color);
    }
    .score-max {
      font-size: 1rem;
      color: #6b7280;
    }
    .score-label {
      font-size: 1.25rem;
      font-weight: 600;
    }
    .score-subtitle {
      font-size: 0.875rem;
      color: #6b7280;
      margin-top: 0.25rem;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
      gap: 1rem;
    }
    .stat-card {
      background: #f9fafb;
      border-radius: 8px;
      padding: 1rem;
      text-align: center;
    }
    .stat-value {
      display: block;
      font-size: 1.5rem;
      font-weight: bold;
    }
    .stat-label {
      display: block;
      font-size: 0.75rem;
      color: #6b7280;
      text-transform: uppercase;
    }
    .stat-card.critical .stat-value { color: #dc2626; }
    .stat-card.serious .stat-value { color: #ea580c; }
    .stat-card.moderate .stat-value { color: #ca8a04; }
    .stat-card.minor .stat-value { color: #2563eb; }
    .findings {
      margin-bottom: 2rem;
    }
    .findings h2 {
      margin-bottom: 1rem;
    }
    .no-findings {
      background: #ecfdf5;
      color: #059669;
      padding: 1rem;
      border-radius: 8px;
      text-align: center;
    }
    .finding {
      background: white;
      border-radius: 8px;
      padding: 1.5rem;
      margin-bottom: 1rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      border-left: 4px solid;
    }
    .finding.critical { border-left-color: #dc2626; }
    .finding.serious { border-left-color: #ea580c; }
    .finding.moderate { border-left-color: #ca8a04; }
    .finding.minor { border-left-color: #2563eb; }
    .finding-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 0.75rem;
    }
    .finding-header h3 {
      font-size: 1rem;
    }
    .impact-badge {
      font-size: 0.75rem;
      font-weight: 600;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      text-transform: uppercase;
    }
    .impact-badge.critical { background: #fef2f2; color: #dc2626; }
    .impact-badge.serious { background: #fff7ed; color: #ea580c; }
    .impact-badge.moderate { background: #fefce8; color: #ca8a04; }
    .impact-badge.minor { background: #eff6ff; color: #2563eb; }
    .finding-description {
      color: #4b5563;
      margin-bottom: 1rem;
    }
    .finding-details {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      margin-bottom: 1rem;
    }
    .detail code {
      background: #f3f4f6;
      padding: 0.125rem 0.375rem;
      border-radius: 4px;
      font-size: 0.875rem;
    }
    .wcag-tag {
      display: inline-block;
      background: #e0e7ff;
      color: #4f46e5;
      padding: 0.125rem 0.375rem;
      border-radius: 4px;
      font-size: 0.75rem;
      margin-right: 0.25rem;
    }
    .finding-html {
      margin-bottom: 1rem;
    }
    .finding-html pre {
      background: #1f2937;
      color: #e5e7eb;
      padding: 1rem;
      border-radius: 4px;
      overflow-x: auto;
      margin-top: 0.5rem;
    }
    .finding-html code {
      font-size: 0.875rem;
    }
    .help-link {
      color: #2563eb;
      font-size: 0.875rem;
    }
    .pages {
      margin-bottom: 2rem;
    }
    .pages h2 {
      margin-bottom: 1rem;
    }
    .pages-table {
      width: 100%;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      border-collapse: collapse;
    }
    .pages-table th,
    .pages-table td {
      padding: 0.75rem 1rem;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    .pages-table th {
      background: #f9fafb;
      font-weight: 600;
      font-size: 0.75rem;
      text-transform: uppercase;
      color: #6b7280;
    }
    .pages-table .url-cell a {
      color: #2563eb;
    }
    .pages-table .score-cell {
      font-weight: 600;
    }
    .pages-table .critical { color: #dc2626; }
    .pages-table .serious { color: #ea580c; }
    .pages-table .moderate { color: #ca8a04; }
    .pages-table .minor { color: #2563eb; }
    .footer {
      text-align: center;
      color: #6b7280;
      font-size: 0.875rem;
    }
    .footer a {
      color: #2563eb;
    }
    @media (max-width: 768px) {
      .container {
        padding: 1rem;
      }
      .finding-details {
        flex-direction: column;
        gap: 0.5rem;
      }
    }
  `;
}
